/**
 * Worker entry (OpenNext's custom worker pattern). It hands each request to the pipeline in
 * lib/worker/handle-request.ts (canonical host, crawl policy, D1 readiness, edge cache, then
 * OpenNext), with the handler that `opennextjs-cloudflare build` generates as `serve`, the Cache
 * API namespace the edge cache stores pages in, a per-isolate memo of D1's readiness, and the
 * D1 search API (lib/worker/search-api.ts).
 *
 * wrangler.jsonc `main` points here. tsconfig.json excludes this file because `.open-next/`
 * exists only after a Worker build; the pipeline it wires in is type-checked and unit-tested.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNextWorker from './.open-next/worker.js'
import { type DatasetReadinessMemo, d1DatasetReadiness } from './lib/worker/dataset-gate'
import { EDGE_CACHE_NAME } from './lib/worker/edge-cache'
import { handleWorkerRequest, type WorkerRequestEnvironment } from './lib/worker/handle-request'
import { d1SearchApi } from './lib/worker/search-api'

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'

let datasetReadiness: DatasetReadinessMemo | undefined

function log(event: object): void {
  console.info(JSON.stringify(event))
}

export default {
  fetch(
    request: Request,
    env: WorkerRequestEnvironment & { DB?: D1Database },
    ctx: ExecutionContext
  ): Promise<Response> {
    datasetReadiness ??= d1DatasetReadiness(env)
    const readiness = datasetReadiness
    return handleWorkerRequest(request, env, rendered => openNextWorker.fetch(rendered, env, ctx), {
      searchApi: d1SearchApi(env, {
        readiness: () => readiness.current(),
        edgeCache: { context: ctx, openCache: () => caches.open(EDGE_CACHE_NAME) },
        observe: log
      }),
      edgeCache: { context: ctx, openCache: () => caches.open(EDGE_CACHE_NAME) },
      datasetReadiness: () => readiness.current(),
      log
    })
  }
}
