/**
 * Worker entry (OpenNext's custom worker pattern): applies the environment's crawl policy
 * (lib/worker/environment-policy.ts), then answers from the edge cache (lib/worker/edge-cache.ts)
 * or hands the request to the handler that `opennextjs-cloudflare build` generates.
 * wrangler.jsonc `main` points here.
 *
 * tsconfig.json excludes this file because `.open-next/` exists only after a Worker build; the
 * policy and cache it wires in are type-checked and unit-tested.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNextWorker from './.open-next/worker.js'
import { type EdgeCacheEnvironment, serveWithEdgeCache } from './lib/worker/edge-cache'
import { type WorkerEnvironment, withEnvironmentPolicy } from './lib/worker/environment-policy'

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'

export default {
  fetch(
    request: Request,
    env: WorkerEnvironment & EdgeCacheEnvironment,
    ctx: ExecutionContext
  ): Promise<Response> {
    return withEnvironmentPolicy(request, env, () =>
      serveWithEdgeCache(request, env, ctx, rendered => openNextWorker.fetch(rendered, env, ctx))
    )
  }
}
