/**
 * Worker entry (OpenNext's custom worker pattern): applies the environment's crawl policy
 * (lib/worker/environment-policy.ts), then hands the request to the handler that
 * `opennextjs-cloudflare build` generates. wrangler.jsonc `main` points here.
 *
 * tsconfig.json excludes this file because `.open-next/` exists only after a Worker build; the
 * policy it wires in is type-checked and unit-tested.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNextWorker from './.open-next/worker.js'
import { type WorkerEnvironment, withEnvironmentPolicy } from './lib/worker/environment-policy'

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'

export default {
  fetch(request: Request, env: WorkerEnvironment, ctx: ExecutionContext): Promise<Response> {
    return withEnvironmentPolicy(request, env, () => openNextWorker.fetch(request, env, ctx))
  }
}
