name = "boxingundefeated"
compatibility_date = "2025-07-31"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "boxingundefeated-db"
database_id = "local"

# R2 bucket for blob storage
[[r2_buckets]]
binding = "BLOB"
bucket_name = "boxingundefeated-blob"

# KV namespace
[[kv_namespaces]]
binding = "KV"
id = "boxingundefeated-kv"
preview_id = "boxingundefeated-kv-preview"