name = "boxingundefeated"
compatibility_date = "2025-07-31"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "boxingundefeated-localdb"
database_id = "6d6aba1e-bfbc-4101-8a94-387f45c30fcd"
preview_database_id = "DB"

# R2 bucket for blob storage
[[r2_buckets]]
binding = "BLOB"
bucket_name = "boxingundefeated-blob"

# KV namespace
[[kv_namespaces]]
binding = "KV"
id = "boxingundefeated-kv"
preview_id = "boxingundefeated-kv-preview"