[[d1_databases]]
binding = "D1"
database_name = "boxingundefeated-com"
database_id = "6b463a07-05a9-4da1-9637-f8331d40b36c"
preview_database_id = "9dde6ccf-fc52-41a3-9268-1a92dabaafb7"
migrations_dir = "server/db/migrations"